version: '3.8'

networks:
    backend-network:
        driver: bridge
    frontend-network:
        driver: bridge

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_HOST: ${DB_HOST}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PORT: ${DB_PORT}
        ports:
            - '127.0.0.1:${DB_PORT}:3306'
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - backend-network

    laravel:
        container_name: laravel
        build:
            context: .
            dockerfile: docker/laravel/Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - '9000:9000'
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - backend-network
        depends_on:
            - mysql

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - '0.0.0.0:80:80'
            - '0.0.0.0:443:443'
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend-network
        depends_on:
            - laravel

    react:
        container_name: react
        build:
            context: .
            dockerfile: docker/react/Dockerfile
        restart: unless-stopped
        volumes:
            - ./react:/app
        ports:
            - "5173:5173"
        networks:
            - frontend-network

volumes:
    db-volume:
        driver: local

