version: '3.8'

networks:
    app-network:
        driver: bridge

services:
    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - app-network

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - '0.0.0.0:80:80'
            - '0.0.0.0:443:443'
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_HOST: ${DB_HOST}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PORT: ${DB_PORT}
        ports:
            - '127.0.0.1:${DB_PORT}:${DB_PORT}'
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - app-network
